### ISSUE TITLE
Country ISO codes data types

### ISSUE THREAD

**Issue by pvdbosch** [belgif/openapi-location#2]
Which country ISO codes do we want to include in our schemas?

* ISO 3166-1 alpha 2: for country names (current only)
  * most used internationally
  * limitations:
    * meaning of a code can change over time (can be reused for new country after x years)
    * change when country renamed
    * only exist from 1974 onwards
    * should not be used for former countries

* ISO 3166-1 numeric-3: for countries
  * most stable identifier, doesn't change over time
  * limitations:
    * only exist for countries from 1981 onwards
    * could be used for former countries in practice, but seems like they shouldn't according to ISO

* ISO 3166-3 (4 letter code) for former country names
  * should be used for former countries
  * used in some international exchanges (e.g. EESSI project)
  * created for country names removed from ISO 3166-1 alpha2, including renamed ones
  * only exist from 1974 onwards

Semantics of their proper use (address, historical, nationality) and mapping to NIS-code depends on fed-voc discussion: https://github.com/belgif/fedvoc/issues/4

CountryNisCode is already defined in schemas, and used in NR/CBSS authentic sources.

**Comment by pvdbosch** [comment]
functionalWG proposes two types (Concept Schemes):

CountryIsoCode: 2 letter
CountryWithHistoricIsoCode: 2 letter + 4 letter

Both can be used both in context of nationality (= citizenship) and place, depending whether a use case allows for historical data.

Other types of country ISO 3166-1 codes are less used (alpha-3 or num-3) so aren't included.

Added the types to the v1beta schema. Before promoting to v1, should be published as proposed standard in fedvoc, and requires validation of REST design WG.

**Comment by bertvannuffelen** [comment]
[3:51 PM] Bert Van Nuffelen
in https://op.europa.eu/en/web/eu-vocabularies/authority-tables
Authority tables - EU Vocabularies - Publications Office of the EU
In order to harmonise and standardise the codes and the associated labels used in the Publications Office and for inter-institutional data exchange, a number of Named Authority Lists (NALs) have be...

[3:51 PM] Bert Van Nuffelen
vind je https://op.europa.eu/en/web/eu-vocabularies/at-dataset/-/resource/dataset/country
country - EU Vocabularies - Publications Office of the EU

**Comment by pvdbosch** [comment]
Reviewed and okayed by REST design WG. Awaiting publication as proposed standard in fedvoc list before promotion from v1beta to v1.

**Comment by pvdbosch** [comment]
published in fedvoc and promoted to stable/v1. Will be part of next release.
